name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: python -m pip install networkx
      - run: python -m unittest

  parsing_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Echo PWD
        run: echo $PWD

      - run: python -m pip install tree-sitter
      - run: python -m pip install networkx
      - run: ./scripts/test_parsing.sh
